-- ==========================================
-- SETUP REGISTRY SETTINGS FOR DYNAMIC CONFIGS
-- Run this script in your Supabase SQL Editor.
-- ==========================================

-- 1. Create Offices Table
CREATE TABLE IF NOT EXISTS public.offices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Payment Methods Table
CREATE TABLE IF NOT EXISTS public.payment_methods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Payment Receivers Table
CREATE TABLE IF NOT EXISTS public.payment_receivers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Create Payment Note Templates Table
CREATE TABLE IF NOT EXISTS public.payment_note_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Create University Statuses Table
CREATE TABLE IF NOT EXISTS public.university_statuses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    color_class TEXT DEFAULT 'text-blue-500'::text NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.offices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_methods ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_receivers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_note_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.university_statuses ENABLE ROW LEVEL SECURITY;

-- Setup RLS Policies for Authenticated Users (Read & Write access)
CREATE POLICY "Allow authenticated read on offices" ON public.offices FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated insert on offices" ON public.offices FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow authenticated update on offices" ON public.offices FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Allow authenticated delete on offices" ON public.offices FOR DELETE TO authenticated USING (true);

CREATE POLICY "Allow authenticated read on payment_methods" ON public.payment_methods FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated insert on payment_methods" ON public.payment_methods FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow authenticated update on payment_methods" ON public.payment_methods FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Allow authenticated delete on payment_methods" ON public.payment_methods FOR DELETE TO authenticated USING (true);

CREATE POLICY "Allow authenticated read on public.payment_receivers" ON public.payment_receivers FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated insert on public.payment_receivers" ON public.payment_receivers FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow authenticated update on public.payment_receivers" ON public.payment_receivers FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Allow authenticated delete on public.payment_receivers" ON public.payment_receivers FOR DELETE TO authenticated USING (true);

CREATE POLICY "Allow authenticated read on payment_note_templates" ON public.payment_note_templates FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated insert on payment_note_templates" ON public.payment_note_templates FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow authenticated update on payment_note_templates" ON public.payment_note_templates FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Allow authenticated delete on payment_note_templates" ON public.payment_note_templates FOR DELETE TO authenticated USING (true);

CREATE POLICY "Allow authenticated read on university_statuses" ON public.university_statuses FOR SELECT TO authenticated USING (true);
CREATE POLICY "Allow authenticated insert on university_statuses" ON public.university_statuses FOR INSERT TO authenticated WITH CHECK (true);
CREATE POLICY "Allow authenticated update on university_statuses" ON public.university_statuses FOR UPDATE TO authenticated USING (true);
CREATE POLICY "Allow authenticated delete on university_statuses" ON public.university_statuses FOR DELETE TO authenticated USING (true);

-- Seed Initial Values
INSERT INTO public.offices (name)
VALUES ('ANDIJON OFFIS'), ('TOSHKENT OFFIS')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.payment_methods (name)
VALUES ('Karta J.A'), ('Karta Abdulaziz'), ('Naqd'), ('Karta M.A'), ('Bank'), ('Discount')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.payment_receivers (name)
VALUES ('ABDULAZIZ'), ('MUSLIHIDDIN'), ('BAXTIYOR'), ('MUHAMMADALI'), ('JASUR'), ('ADMIN'), ('Discount')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.payment_note_templates (name)
VALUES ('Shartnoma uchun'), ('Qarz'), ('Elchixona uchun'), ('Appfee'), ('DISCOUNT')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.university_statuses (name, color_class)
VALUES 
    ('Chosen', 'text-blue-500'),
    ('Applying', 'text-amber-500'),
    ('Applied', 'text-amber-500'),
    ('Accepted', 'text-emerald-500'),
    ('Failed', 'text-rose-500')
ON CONFLICT (name) DO NOTHING;
