-- ------------------------------------------------------------
-- Settings Options Tables (Tariff, Level, Group, Lead Source)
-- Run this in the Supabase SQL Editor (Dashboard → SQL Editor)
-- ------------------------------------------------------------

ALTER TABLE public.students DROP CONSTRAINT IF EXISTS students_tariff_check;
ALTER TABLE public.students DROP CONSTRAINT IF EXISTS students_level_check;
ALTER TABLE public.students DROP CONSTRAINT IF EXISTS students_level2_check;
ALTER TABLE public.students DROP CONSTRAINT IF EXISTS students_language_certificate_check;
ALTER TABLE public.students DROP CONSTRAINT IF EXISTS students_language_certificate_2_check;
ALTER TABLE public.students DROP CONSTRAINT IF EXISTS students_language_certificate_3_check;


-- 2. Create tables for settings options
CREATE TABLE IF NOT EXISTS public.tariff_options (
  id          BIGSERIAL   PRIMARY KEY,
  name        TEXT        UNIQUE NOT NULL,
  price       NUMERIC     NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.education_levels (
  id          BIGSERIAL   PRIMARY KEY,
  name        TEXT        UNIQUE NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.student_groups (
  id          BIGSERIAL   PRIMARY KEY,
  name        TEXT        UNIQUE NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.lead_sources (
  id          BIGSERIAL   PRIMARY KEY,
  name        TEXT        UNIQUE NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. Enable RLS
ALTER TABLE public.tariff_options ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.education_levels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lead_sources ENABLE ROW LEVEL SECURITY;

-- 4. Create RLS Policies for full authenticated access
DROP POLICY IF EXISTS "tariff_options: authenticated access" ON public.tariff_options;
CREATE POLICY "tariff_options: authenticated access" ON public.tariff_options FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "education_levels: authenticated access" ON public.education_levels;
CREATE POLICY "education_levels: authenticated access" ON public.education_levels FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "student_groups: authenticated access" ON public.student_groups;
CREATE POLICY "student_groups: authenticated access" ON public.student_groups FOR ALL TO authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "lead_sources: authenticated access" ON public.lead_sources;
CREATE POLICY "lead_sources: authenticated access" ON public.lead_sources FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- 5. Insert Seed Data
INSERT INTO public.tariff_options (name, price) VALUES
  ('STANDART', 13000000),
  ('PREMIUM', 32500000),
  ('VISA PLUS', 65000000),
  ('E-VISA (TIL SERTIFIKATISIZ)', 24000000),
  ('E-VISA (TIL SERTIFIKATLI)', 16000000),
  ('REGIONAL VISA', 24000000),
  ('ZERO RISK', 18500000)
ON CONFLICT (name) DO UPDATE SET price = EXCLUDED.price;

INSERT INTO public.education_levels (name) VALUES
  ('BACHELOR'),
  ('COLLEGE'),
  ('LANGUAGE COURSE'),
  ('MASTER NO CERTIFICATE'),
  ('MASTERS')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.student_groups (name) VALUES
  ('2026 BAHOR'),
  ('2026 KUZ'),
  ('2027 BAHOR')
ON CONFLICT (name) DO NOTHING;

INSERT INTO public.lead_sources (name) VALUES
  ('Ali Uncle'),
  ('Cornell'),
  ('Headway'),
  ('SeoulStudy'),
  ('UP Marhamat')
ON CONFLICT (name) DO NOTHING;

-- 6. Create Universities table
CREATE TABLE IF NOT EXISTS public.universities (
  id          BIGSERIAL   PRIMARY KEY,
  name        TEXT        UNIQUE NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.universities ENABLE ROW LEVEL SECURITY;

-- Create RLS Policies
DROP POLICY IF EXISTS "universities: authenticated access" ON public.universities;
CREATE POLICY "universities: authenticated access" ON public.universities FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Insert Universities Seed Data
INSERT INTO public.universities (name) VALUES
  ('AJOU UNIVERSITY (SUWON, GYEONGGI)'),
  ('ANSAN UNIVERSITY (ANSAN, GYEONGGI)'),
  ('ANYANG UNIVERSITY (ANYANG, GYEONGGI)'),
  ('BAEKSEOK UNIVERSITY (CHEONAN, CHUNGNAM)'),
  ('BUCHEON UNIVERSITY (BUCHEON, GYEONGGI)'),
  ('BUSAN INSTITUTE OF SCIENCE AND TECHNOLOGY (BUK-GU, BUSAN)'),
  ('BUSAN UNIVERSITY OF FOREIGN STUDIES (GEUMJEONG, BUSAN)'),
  ('CATHOLIC UNIVERSITY OF KOREA (BUCHEON, GYEONGGI)'),
  ('CHA UNIVERSITY (PANGYO, GYEONGGI)'),
  ('CHANGSHIN UNIVERSITY (MASAN, GYEONGNAM)'),
  ('CHANGWON NATIONAL UNIVERSITY (CHANGWON, GYEONGNAM)'),
  ('CHEONGAM UNIVERSITY (SUNCHEON, JEONNAM)'),
  ('CHEONGJU UNIVERSITY (CHEONGJU, CHUNGBUK)'),
  ('CHONNAM NATIONAL UNIVERSITY (BUK-GU, GWANGJU)'),
  ('CHOSUN UNIVERSITY (DONG-GU, GWANGJU)'),
  ('CHUNG-ANG UNIVERSITY (DONGJAK, SEOUL)'),
  ('CHUNGBUK HEALTH & SCIENCE UNIVERSITY (CHEONJU, CHUNGBUK)'),
  ('CHUNGBUK NATIONAL UNIVERSITY (CHEONGJU, CHUNGBUK)'),
  ('CHUNGCHEONG COLLEGE (CHEONGJU, CHUNCHEONG-BUK DO)'),
  ('CHUNGNAM NATIONAL UNIVERSITY (YUSEONG, DAEJEON)'),
  ('DAEGU CATHOLIC UNIVERSITY (GYEONGSAN, GYEONGBUK)'),
  ('DAEGU HAANY UNIVERSITY (GYEONGSAN, GYEONGBUK)'),
  ('DAEGU UNIVERSITY (GYEONGSAN, GYEONGBUK)'),
  ('DAEJEON UNIVERSITY (DONG-GU, DAEJEON)'),
  ('DAEJIN UNIVERSITY (POCHEON, GYEONGGI)'),
  ('DAELIM UNIVERSITY (ANYANG, GYEONGGI)'),
  ('DAESHIN UNIVERSITY (GYEONGSAN, GYEONGBUK)'),
  ('DAEWON UNIVERSITY COLLEGE (JECHEON, CHUNGBUK)'),
  ('DONG EUI COLLEGE (BUSANJIN, BUSAN)'),
  ('DONG-A UNIVERSITY (SAHA, BUSAN)'),
  ('DONG-EUI INSTITUTE OF TECHNOLOGY (BUSANJIN, BUSAN)'),
  ('DONG-EUI UNIVERSITY (BUSANJIN, BUSAN)'),
  ('DONGDUK WOMEN''S UNIVERSITY (SEONGBUK, SEOUL)'),
  ('DONGGUK UNIVERSITY (JUNG-GU, SEOUL)'),
  ('DONGSEO UNIVERSITY (SASANG, BUSAN)'),
  ('DONGSHIN UNIVERSITY (NAJU, JEONNAM)'),
  ('DONGWON INSTITUTE OF SCIENCE AND TECHNOLOGY (YANGSAN, GYEONGNAM)'),
  ('DUKSUNG WOMEN''S UNIVERSITY (DOBONG, SEOUL)'),
  ('EULJI UNIVERSITY (SEONGNAM, GYEONGGI)'),
  ('EWHA WOMANS UNIVERSITY (SEODAEMUN, SEOUL)'),
  ('FAR EAST UNIVERSITY (EUMSEONG, CHUNGBUK)'),
  ('GACHON UNIVERSITY (SEONGNAM, GYEONGGI)'),
  ('GANGNAM UNIVERSITY (YONGIN, GYEONGGI)'),
  ('GANGNEUNG-WONJU NATIONAL UNIVERSITY (GANGNEUNG, GANGWON)'),
  ('GANGSEO UNIVERSITY (GANGSEO, SEOUL)'),
  ('GIMCHEON UNIVERSITY (GIMCHEON, GYEONGBUK)'),
  ('GONGJU NATIONAL UNIVERSITY (GONGJU, CHUNGNAM)'),
  ('GUNJANG UNIVERSITY (GUNSAN, JEONBUK)'),
  ('GWANGJU INSTITUTE OF SCIENCE AND TECHNOLOGY (BUK-GU, GWANGJU)'),
  ('GWANGJU UNIVERSITY (NAM-GU, GWANGJU)'),
  ('GWANGJU WOMEN''S UNIVERSITY (GWANGSAN, GWANGJU)'),
  ('GYEONGIN WOMEN''S UNIVERSITY (GYEYANG, INCHEON)'),
  ('GYEONGSANG NATIONAL UNIVERSITY (JINJU, GYEONGNAM)'),
  ('HALLYM UNIVERSITY (CHUNCHEON, GANGWON)'),
  ('HANBAT NATIONAL UNIVERSITY (YUSEONG, DAEJEON)'),
  ('HANDONG GLOBAL UNIVERSITY (BUK-GU, POHANG)'),
  ('HANKUK UNIVERSITY OF FOREIGN STUDIES (DONGDAEMUN, SEOUL)'),
  ('HANNAM UNIVERSITY (DAEDEOK, DAEJEON)'),
  ('HANSEI UNIVERSITY (GUNPO, GYEONGGI)'),
  ('HANSEO UNIVERSITY (SEOSAN, CHUNGNAM)'),
  ('HANSUNG UNIVERSITY (SEONGBUK, SEOUL)'),
  ('HANYANG UNIVERSITY (SEONGDONG, SEOUL)'),
  ('HANYANG WOMEN''S UNIVERSITY (SEONGDONG, SEOUL)'),
  ('HONGIK UNIVERSITY (MAPO, SEOUL)'),
  ('HOSEO UNIVERSITY (ASAN, CHUNGNAM)'),
  ('INCHEON UNIVERSITY (YEONSU, INCHEON)'),
  ('INDUK UNIVERSITY (NOWON, SEOUL)'),
  ('INHA TECHNICAL COLLEGE (1%)'),
  ('INHA UNIVERSITY (MICHUHOL, INCHEON)'),
  ('INJE UNIVERSITY (GIMHAE, GYEONGNAM)'),
  ('JANGAN UNIVERSITY (HWASEONG, GYEONGGI)'),
  ('JEJU HALLA UNIVERSITY (JEJU, JEJU)'),
  ('JEJU TOURISM UNIVERSITY (JEJU, JEJU)'),
  ('JEONBUK NATIONAL UNIVERSITY (DEOKJIN, JEONJU)'),
  ('JEONBUK SCIENCE COLLEGE (JEONGEUP, JEONBUK)'),
  ('JEONJU UNIVERSITY (WANSAN, JEONJU)'),
  ('JEONJU VISION UNIVERSITY (WANSAN, JEONJU)'),
  ('JEONNAM NATIONAL UNIVERSITY (BUK-GU, GWANGJU)'),
  ('JOONGBU UNIVERSITY (GEUMSAN, CHUNGNAM)'),
  ('JUNGWON UNIVERSITY (GOESAN, CHUNGBUK)'),
  ('KAIST (YUSEONG, DAEJEON)'),
  ('KANGWON NATIONAL UNIVERSITY (CHUNCHEON, GANGWON)'),
  ('KEIMYUNG COLLEGE UNIVERSITY (DALSEO, DAEGU)'),
  ('KEIMYUNG UNIVERSITY (DALSEO, DAEGU)'),
  ('KONKUK UNIVERSITY (GWANGJIN, SEOUL)'),
  ('KOOKMIN UNIVERSITY (SEONGBUK, SEOUL)'),
  ('KOREA MARITIME AND OCEAN UNIVERSITY (YEONGDO, BUSAN)'),
  ('KOREA NATIONAL UNIVERSITY OF EDUCATION (CHEONGJU, CHUNGBUK)'),
  ('KOREA NATIONAL UNIVERSITY OF TRANSPORTATION (CHUNGJU, CHUNGBUK)'),
  ('KOREA UNIVERSITY (SEONGBUK, SEOUL)'),
  ('KOREA UNIVERSITY OF MEDIA ARTS (CHEONAN, CHUNGNAM)'),
  ('KOREA UNIVERSITY OF TECHNOLOGY AND EDUCATION (CHEONAN, CHUNGNAM)'),
  ('KOREAN AEROSPACE UNIVERSITY (GOYANG, GYEONGGI)'),
  ('KOREAN BIBLE UNIVERSITY (NOWON, SEOUL)'),
  ('KOSIN UNIVERSITY (YEONGDO, BUSAN)'),
  ('KUMOH NATIONAL INSTITUTE OF TECHNOLOGY (GUMI, GYEONGBUK)'),
  ('KUNJANG UNIVERSITY COLLEGE (GUNSAN, JEONBUK)'),
  ('KUNSAN NATIONAL UNIVERSITY (GUNSAN, JEONBUK)'),
  ('KWANGWOON UNIVERSITY (NOWON, SEOUL)'),
  ('KYONGGI UNIVERSITY (SUWON, GYEONGGI)'),
  ('KYUNG HEE UNIVERSITY (DONGDAEMUN, SEOUL)'),
  ('KYUNGBOK UNIVERSITY (NAMYANGJU, GYEONGGI)'),
  ('KYUNGDONG UNIVERSITY (GOSEONG, GANGWON)'),
  ('KYUNGIL UNIVERSITY (GYEONGSAN, GYEONGBUK)'),
  ('KYUNGNAM UNIVERSITY (CHANGWON, GYEONGNAM)'),
  ('KYUNGPOOK NATIONAL UNIVERSITY (BUK-GU, DAEGU)'),
  ('KYUNGWOON UNIVERSITY (GUMI, GYEONGBUK)'),
  ('MOKPO NATIONAL UNIVERSITY (MOKPO, JEONNAM)'),
  ('MOKPO SCIENCE UNIVERSITY (MOKPO, JEONNAM)'),
  ('MOKWON UNIVERSITY (SEO-GU, DAEJEON)'),
  ('MYONGJI COLLEGE (SEODAEMUN, SEOUL)'),
  ('MYONGJI UNIVERSITY (YONGIN, GYEONGGI)'),
  ('NAMSEOUL UNIVERSITY (CHEONAN, CHUNGNAM)'),
  ('NAZARENE UNIVERSITY (CHEONAN, CHUNGNAM)'),
  ('OSAN UNIVERSITY (OSAN, GYEONGGI)'),
  ('PAICHAI UNIVERSITY (SEO-GU, DAEJEON)'),
  ('POSTECH (NAM-GU, POHANG)'),
  ('PUKYONG NATIONAL UNIVERSITY (NAM-GU, BUSAN)'),
  ('PUSAN NATIONAL UNIVERSITY (GEUMJEONG, BUSAN)'),
  ('PYEONGTAEK UNIVERSITY (PYEONGTAEK, GYEONGGI)'),
  ('SAHMYOOK UNIVERSITY (NOWON, SEOUL)'),
  ('SEJONG UNIVERSITY (GWANGJIN, SEOUL)'),
  ('SEMYUNG UNIVERSITY (JECHEON, CHUNGBUK)'),
  ('SEOJEONG UNIVERSITY (YANGJU, GYEONGGI)'),
  ('SEOUL CHRISTIAN UNIVERSITY (SEODAEMUN, SEOUL)'),
  ('SEOUL INSTITUTE OF THE ARTS (ANSAN, GYEONGGI)'),
  ('SEOUL MEDIA INSTITUTE OF TECHNOLOGY (SMIT) (GANGSEO, SEOUL)'),
  ('SEOUL NATIONAL UNIVERSITY (GWANAK, SEOUL)'),
  ('SEOUL NATIONAL UNIVERSITY OF SCIENCE AND TECHNOLOGY (NOWON, SEOUL)'),
  ('SEOYEONG UNIVERSITY (PAJU, GYEONGGI)'),
  ('SHINHAN UNIVERSITY (UIJEONGBU, GYEONGGI)'),
  ('SILLA UNIVERSITY (SASANG, BUSAN)'),
  ('SOGANG UNIVERSITY (MAPO, SEOUL)'),
  ('SOONCHUNHYANG UNIVERSITY (ASAN, CHUNGNAM)'),
  ('SOONGSIL UNIVERSITY (DONGJAK, SEOUL)'),
  ('SUN MOON UNIVERSITY (ASAN, CHUNGNAM)'),
  ('SUNCHEON JEIL COLLEGE (SUNCHEON, JEONNAM)'),
  ('SUNGKONGHOE UNIVERSITY (GURO, SEOUL)'),
  ('SUNGKYUNKWAN UNIVERSITY (JONGNO, SEOUL)'),
  ('SUNGSHIN WOMENS UNIVERSITY (SEONGBUK, SEOUL)'),
  ('TONGMYONG UNIVERSITY (NAM-GU, BUSAN)'),
  ('TONGWON UNIVERSITY (GWANGJU, GYEONGGI)'),
  ('UIDUK UNIVERSITY (GYEONGJU, GYEONGBUK)'),
  ('UNIVERSITY OF ULSAN (NAM-GU, ULSAN)'),
  ('WONKWANG HEALTH SCIENCE UNIVERSITY (IKSAN, JEONBUK)'),
  ('WONKWANG UNIVERSITY (IKSAN, JEONBUK)'),
  ('WOOSONG UNIVERSITY (DONG-GU, DAEJEON)'),
  ('WOOSUK UNIVERSITY (WANJU, JEONBUK)'),
  ('YEUNGJIN UNIVERSITY (BUK-GU, DAEGU)'),
  ('YEUNGNAM UNIVERSITY (GYEONGSAN, GYEONGBUK)'),
  ('YEUNGNAM UNIVERSITY COLLEGE (NAM-GU, DAEGU)'),
  ('YONG-IN ARTS AND SCIENCE UNIVERSITY (YONGIN, GYEONGGI)'),
  ('YONSEI UNIVERSITY (SEODAEMUN, SEOUL)'),
  ('YONSEI UNIVERSITY MIRAE CAMPUS (WONJU, GANGWON)'),
  ('YOUNG-SAN UNIVERSITY (YANGSAN, GYEONGNAM)')
ON CONFLICT (name) DO NOTHING;
