INSERT INTO schools (name, address, website, phone, email, source) VALUES
  ('"COLLEGIUM HUMANUM" WARSAW MANAGEMENT UNIVERSITY, ANDIJAN BRANCH', 'Andijon viloyati, Andijon shahri, O''zbekiston Paxtakor МFY, A.Yuldashev ko''chasi, 58-a-uy', 'https://tuab.uz/', '742000025', 'turonuniversityandijan@gmail.com', 'seed'),
  ('ABU RAYHON BERUNIY UNIVERSITY', NULL, NULL, NULL, NULL, 'seed'),
  ('ACADEMY OF PUBLIC ADMINISTRATION', NULL, NULL, NULL, NULL, 'seed'),
  ('ACADEMY OF THE ARMED FORCES OF THE REPUBLIC OF UZBEKISTAN', NULL, NULL, NULL, NULL, 'seed'),
  ('ACADEMY OF THE MINISTRY OF EMERGENCY SITUATIONS OF THE REPUBLIC OF UZBEKISTAN', NULL, NULL, NULL, NULL, 'seed'),
  ('ACADEMY OF THE MINISTRY OF INTERNAL AFFAIRS OF THE REPUBLIC OF UZBEKISTAN', NULL, NULL, NULL, NULL, 'seed'),
  ('ACADEMY OF THE STATE SECURITY SERVICE OF THE REPUBLIC OF UZBEKISTAN', NULL, NULL, NULL, NULL, 'seed'),
  ('AJU UNIVERSITY IN TASHKENT', NULL, NULL, NULL, NULL, 'seed'),
  ('AKFA UNIVERSITY', NULL, NULL, NULL, NULL, 'seed'),
  ('ALL-RUSSIAN STATE INSTITUTE OF CINEMATOGRAPHY, TASHKENT BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('AMITY UNIVERSITY IN TASHKENT', NULL, NULL, NULL, NULL, 'seed'),
  ('ANDIJAN INSTITUTE OF AGRICULTURE AND AGROTECHNOLOGIES', 'Andijan viloyati, Kuyganyor, Oliygoh ko''chasi 1-uy', 'https://andqxai.uz', '743731363', 'admission@andqxai.uz', 'seed'),
  ('ANDIJAN INSTITUTE OF ECONOMICS AND CONSTRUCTION', NULL, NULL, NULL, NULL, 'seed'),
  ('ANDIJAN MACHINE-BUILDING INSTITUTE', NULL, NULL, NULL, NULL, 'seed'),
  ('ANDIJAN MEDICAL INSTITUTE', 'Andijon shahar, Yu.Otabekov ko''chasi, 1-uy', 'https://adti.uz', '742239460', 'info@adti.uz', 'seed'),
  ('ANDIJAN STATE UNIVERSITY', 'O''zbekiston Respublikasi, Andijon shahar, Universitet ko''chasi 129-uy', 'https://adu.uz', '742238814', 'agsu_info@edu.uz', 'seed'),
  ('ANDIJAN STATE UNIVERSITY, PEDAGOGICAL INSTITUTE', 'Andijon viloyati, Andijon shahri, Do‘stlik ko‘chasi, 4-uy', 'https://adpi.uz', '742240170', 'adpi@edu.uz', 'seed'),
  ('ASTRAKHAN STATE TECHNICAL UNIVERSITY, TASHKENT BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('BANKING AND FINANCE ACADEMY', NULL, NULL, NULL, NULL, 'seed'),
  ('BINARY UNIVERSITY IN URGENCH', NULL, NULL, NULL, NULL, 'seed'),
  ('BRITISH MANAGEMENT UNIVERSITY IN TASHKENT', NULL, NULL, NULL, NULL, 'seed'),
  ('BUKHARA INSTITUTE OF ENGINEERING AND TECHNOLOGY', NULL, NULL, NULL, NULL, 'seed'),
  ('BUKHARA MEDICAL INSTITUTE', 'Buxoro shahar, A.Navoiy ko''chasi, 1-uy', 'https://bsmi.uz', '652230050', 'info@bsmi.uz', 'seed'),
  ('BUKHARA STATE UNIVERSITY', 'Buxoro sh. M.Iqbol ko`chasi 11-uy', 'https://buxdu.uz', '652212914', 'buxdu_rektor@buxdu.uz', 'seed'),
  ('BUKHARA STATE UNIVERSITY, PEDAGOGICAL INSTITUTE', 'Buxoro shahar Piridastgir ko`chasi 2-uy', 'https://buxdpi.uz', '652261097', 'buxdpi@buxdpi.uz', 'seed'),
  ('CAMBRIDGE INTERNATIONAL UNIVERSITY IN TASHKENT', NULL, NULL, NULL, NULL, 'seed'),
  ('CHIRCHIQ STATE PEDAGOGICAL UNIVERSITY OF TASHKENT REGION', 'Toshkent viloyati, Chirchiq shahri, Amir Temur ko''chasi 104 uy', 'https://www.cspi.uz', '707166805', 'tvchdpi@edu.uz', 'seed'),
  ('D. I. MENDELEEV RUSSIAN UNIVERSITY OF CHEMICAL TECHNOLOGY, TASHKENT BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('FERGANA MEDICAL INSTITUTE OF PUBLIC HEALTH', 'Fargʻona sh, Yangi Turon, 2-a uy', 'https://fjsti.uz', '952022345', 'info@fjsti.uz', 'seed'),
  ('FERGANA POLYTECHNIC INSTITUTE', NULL, NULL, NULL, NULL, 'seed'),
  ('FERGANA STATE UNIVERSITY', 'Farg`ona shahri, Murabbiylar ko`chasi, 19-uy', 'https://fdu.uz', '732444402', 'fardu_info@umail.uz', 'seed'),
  ('G. V. PLEKHANOV RUSSIAN UNIVERSITY OF ECONOMICS, TASHKENT BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('GULISTAN STATE UNIVERSITY', 'Guliston sh. 4 mavze', 'https://guldu.uz', '672254042', 'glsu_info@edu.uz', 'seed'),
  ('HIGHER MILITARY CUSTOMS INSTITUTE', NULL, NULL, NULL, NULL, 'seed'),
  ('HIGHER SCHOOL OF NATIONAL DANCE AND CHOREOGRAPHY', NULL, NULL, NULL, NULL, 'seed'),
  ('HIGHER SCHOOL OF STRATEGIC ANALYSIS AND FORESIGHT', NULL, NULL, NULL, NULL, 'seed'),
  ('I. M. GUBKIN RUSSIAN UNIVERSITY OF OIL AND GAS, TASHKENT BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('INHA UNIVERSITY IN TASHKENT', NULL, NULL, NULL, NULL, 'seed'),
  ('INTERNATIONAL AGRICULTURE UNIVERSITY', 'Toshkent shahri, Yunusobod tumani, Universitet ko‘chasi, 2-uy', 'https://iau.uz/', '999810919', 'info@iau.uz', 'seed'),
  ('INTERNATIONAL ISLAMIC ACADEMY OF UZBEKISTAN', 'Toshkent 100002,  Abdulla Qodiriy ko‘chasi, 11-uy', 'https://www.iiau.uz', '712449464', NULL, 'seed'),
  ('INTERNATIONAL NORDIC UNIVERSITY', NULL, NULL, NULL, NULL, 'seed'),
  ('ISFT TASHKENT', 'Toshkent viloyati, Qibray tumani, Universitet ko`chasi – 2', 'https://isft.uz', '781473737', 'info@isft.uz', 'seed'),
  ('IT-PARK UNIVERSITY', NULL, NULL, NULL, NULL, 'seed'),
  ('JIZZAKH AVIATION HIGHER MILITARY SCHOOL', NULL, NULL, NULL, NULL, 'seed'),
  ('JIZZAKH POLYTECHNIC INSTITUTE', 'Jizzax viloyati Jizzax shaxri Islom Karimov ko’chasi 4 uy.', 'https://jizpi.uz', '722264605', 'dgpi_info@edu.uz', 'seed'),
  ('JIZZAKH STATE PEDAGOGICAL UNIVERSITY', 'Jizzax viloyati, Jizzax shahri, Sharof Rashidov ko''chasi, 4-uy.', 'https://jdpu.uz', '722261357', 'jiz.jdpi@exat.uz', 'seed'),
  ('KARAKALPAK STATE UNIVERSITY', 'Qoraqalpog''iston Respublikasi, Nukus shahri, Sh.Abdirov ko''chasi 1-uy', 'https://karsu.uz', '612236078', 'karsu_info@edu.uz', 'seed'),
  ('KARAKALPAKSTAN MEDICAL INSTITUTE', 'Qoraqalpog''iston Respublikasi, Nukus, A.Dosnazarov ko''chasi, 108', 'https://kkmi.uz', '612228432', 'nukusmed@mail.ru', 'seed'),
  ('KARSHI STATE TECHNICAL UNIVERSITY', NULL, NULL, NULL, NULL, 'seed'),
  ('KARSHI STATE UNIVERSITY', 'Qarshi shahri, Ko‘chabog‘ ko‘chasi, 17-uy', 'https://qarshidu.uz', '752212104', 'kasu_info@edu.uz', 'seed'),
  ('KAZAN FEDERAL UNIVERSITY, JIZZAKH BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('KOKAND STATE PEDAGOGICAL INSTITUTE', 'Qo''qon shahri, Turon ko''chasi', 'https://kspi.uz', '735423838', 'kspi_info@edu.uz', 'seed'),
  ('KOKAND UNIVERSITY', NULL, NULL, NULL, NULL, 'seed'),
  ('KOREA INTERNATIONAL UNIVERSITY IN FERGANA', NULL, NULL, NULL, NULL, 'seed'),
  ('KUKMIN UNIVERSITY IN ANGREN', NULL, NULL, NULL, NULL, 'seed'),
  ('LATVIAN HIGHER SCHOOL OF INFORMATION SYSTEMS MANAGEMENT, FERGANA BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('M. AUEZOV SOUTH KAZAKHSTAN RESEARCH UNIVERSITY, CHIRCHIQ BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('M. V. LOMONOSOV MOSCOW STATE UNIVERSITY, TASHKENT BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('MILITARY INSTITUTE OF INFORMATION AND COMMUNICATION TECHNOLOGIES AND COMMUNICATIONS OF THE MINISTRY OF DEFENCE OF THE REPUBLIC OF UZBEKISTAN', NULL, NULL, NULL, NULL, 'seed'),
  ('MISIS, ALMALYK BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('MMFI TASHKENT BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('MOSCOW STATE INSTITUTE OF INTERNATIONAL RELATIONS, TASHKENT BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('NAMANGAN INSTITUTE OF ENGINEERING AND CONSTRUCTION', NULL, NULL, NULL, NULL, 'seed'),
  ('NAMANGAN INSTITUTE OF ENGINEERING AND TECHNOLOGY', NULL, NULL, NULL, NULL, 'seed'),
  ('NAMANGAN STATE PEDAGOGICAL INSTITUTE', 'Namangan shaxar, Uychi ko''chasi, 316-uy', 'https://namspi.uz', '692272721', 'info@namspi.uz', 'seed'),
  ('NAMANGAN STATE UNIVERSITY', 'Namangan shaxri, Boburshox ko’chasi 161 uy.', 'https://www.namdu.uz', '692288525', 'info@namdu.uz', 'seed'),
  ('NATIONAL INSTITUTE OF FINE ARTS AND DESIGN', 'Toshkent shahar, Mironshox ko’chasi 123-uy.', 'https://mrdi.uz', '712551892', 'info@mrdi.uz', 'seed'),
  ('NATIONAL UNIVERSITY OF UZBEKISTAN', 'Toshkent shahar, Olmazor tumani, Universitet ko’chasi, 4-uy', 'https://nuu.uz', '712465417', 'DEVONXONA@NUU.UZ', 'seed'),
  ('NATIONAL UNIVERSITY OF UZBEKISTAN, JIZZAKH BRANCH', 'Jizzax shahri, Sharof Rashidov shoh ko‘chasi, 259 uy', 'https://jbnuu.uz', '722260170', 'info@jbnuu.uz', 'seed'),
  ('NAVOI STATE MINING INSTITUTE, ALMALYK FACULTY', NULL, NULL, NULL, NULL, 'seed'),
  ('NAVOI STATE MINING INSTITUTE, NUKUS BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('NAVOI STATE MINING INSTITUTE, ZARAFSHAN FACULTY', NULL, NULL, NULL, NULL, 'seed'),
  ('NAVOI STATE PEDAGOGICAL INSTITUTE', NULL, NULL, NULL, NULL, 'seed'),
  ('NAVOI STATE UNIVERSITY OF MINING AND TECHNOLOGIES', 'Navoiy shahar, G''alabashox ko''chasi', 'https://nsumt.uz', '792235362', 'info@nsumt.uz', 'seed'),
  ('NEW UZBEKISTAN UNIVERSITY', NULL, NULL, NULL, NULL, 'seed'),
  ('NUKUS STATE PEDAGOGICAL INSTITUTE', 'Qoraqolpog‘iston Respublikasi, Nukus shahri, P.Seytov ko‘chasi, raqamsiz uy', 'https://ndpi.uz', '612294075', 'nkspi_info@edu.uz', 'seed'),
  ('OXUS UNIVERSITY', 'Toshkent shahri, Farg‘ona yo‘li ko‘chasi, 25-uy', 'https://www.oxusuniversity.uz/', '781133663', 'info@oxusuniversity.uz', 'seed'),
  ('PDP UNIVERSITY', NULL, NULL, NULL, NULL, 'seed'),
  ('PHARMACEUTICAL TECHNICAL UNIVERSITY', '111809, Toshkent viloyati, Zangiota tumani, Bog''zor MFY, Bog''zor ko''chasi, 1-uy', 'https://ptu.uz/', '559000500', 'info@pharmatechuni.uz', 'seed'),
  ('PUBLIC SAFETY UNIVERSITY OF THE NATIONAL GUARD OF THE REPUBLIC OF UZBEKISTAN', 'Toshkent viloyati, Zangioat tumani, Chorsu qo''rg''ni', 'https://mgjxu.uz', '712303271', 'info@mgjxu.uz', 'seed'),
  ('PUCHON UNIVERSITY IN TASHKENT', NULL, NULL, NULL, NULL, 'seed'),
  ('RUSSIAN STATE UNIVERSITY OF PHYSICAL EDUCATION, SPORT, YOUTH AND TOURISM, SAMARKAND BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('SAINT PETERSBURG STATE UNIVERSITY, TASHKENT BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('SAMARKAND HIGHER MILITARY SCHOOL OF AUTOMOTIVE COMMANDER-ENGINEERS', NULL, NULL, NULL, NULL, 'seed'),
  ('SAMARKAND INSTITUTE OF ECONOMICS AND SERVICE', 'Samarqand viloyati, Shahar: Samarqand, Amir Temur ko''chasi, 9-uy', 'http://sies.uz', '662333873', 'sies_info@edu.uz', 'seed'),
  ('SAMARKAND INSTITUTE OF VETERINARY MEDICINE', 'Toshkent shahar, Chilonzor tumani 20-mavze 35a-uy', 'https://ssuv.uz', '662349873', 'https://www.facebook.com/ssuv.educaton', 'seed'),
  ('SAMARKAND INSTITUTE OF VETERINARY MEDICINE, NUKUS BRANCH', 'Nukus shahar, A. Utepov ko''chasi 31 uy', 'https://sdvunf.uz', '612247109', 'samvminf@edu.uz', 'seed'),
  ('SAMARKAND STATE ARCHITECTURE AND CONSTRUCTION INSTITUTE', 'Samarqand shahri, Lolazor ko''chasi, 70 uy', 'https://www.samgasi.uz', '662371593', 'samdaqu@edu.uz', 'seed'),
  ('SAMARKAND STATE INSTITUTE OF FOREIGN LANGUAGES', 'Samarkand, Bostonsaroy ko''chasi, 93-uy', 'https://samdchti.uz', '662382947', 'info@samdchti.uz', 'seed'),
  ('SAMARKAND STATE MEDICAL INSTITUTE', 'Samarqand sh., Amir Temur k.,18-uy', 'https://www.sammu.uz', '662330841', 'samgmi@mail.ru', 'seed'),
  ('SAMARKAND STATE UNIVERSITY', 'Samarqand shahri, Universitet xiyoboni, 15-uy', 'https://www.samdu.uz', '662403840', 'devonxona@samdu.uz', 'seed'),
  ('SAMARKAND STATE UNIVERSITY, DENOV INSTITUTE OF ENTREPRENEURSHIP AND PEDAGOGY', 'Surxandaryo viloyati, Shahar: Denov, Sh.Rashidov ko''chasi, 360', 'https://dtpi.uz', '956507757', 'info_dtpi@edu.uz', 'seed'),
  ('SAMARKAND STATE UNIVERSITY, KATTAKURGAN BRANCH', 'Samarqand viloyati, Shahar: Kattaqo''rg''on, Amir Temur ko''chasi', 'https://samdukf.uz', '997720809', 'samdukf_devonxona@edu.uz', 'seed'),
  ('SAMARKAND STATE UNIVERSITY, URGUT BRANCH', 'Samarqand viloyati Urgut tumani Vag''ashti MFY 13-uy', 'https://samduuf.uz', '933566070', 'samduuf@edu.uz', 'seed'),
  ('SAMBHRAM UNIVERSITY', NULL, NULL, NULL, NULL, 'seed'),
  ('SAMBHRAM UNIVERSITY, JIZZAKH BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('SHAHRISABZ STATE PEDAGOGICAL INSTITUTE', 'Qashqadaryo Viloyati , Shahrisabz Shahri, Shahrisabz Ko''cha 10-Uy', 'https://shdpi.uz', '755224058', 'info@shdpi.uz', 'seed'),
  ('SHARDA UNIVERSITY IN ANDIJAN', NULL, NULL, NULL, NULL, 'seed'),
  ('SHINHAN UNIVERSITY IN TASHKENT', NULL, NULL, NULL, NULL, 'seed'),
  ('SILK ROAD INTERNATIONAL UNIVERSITY OF TOURISM', 'Samarqand shahri, Universitet xiyoboni, 17-uy', 'https://univ-silkroad.uz', '662406768', 'info@univ-silkroad.uz', 'seed'),
  ('SINGAPORE INSTITUTE OF MANAGEMENT DEVELOPMENT IN TASHKENT', 'Toshkent shahri, Yakkasaroy tumani, Muqimiy ko‘chasi, 41B-uy', 'https://tmci.uz', '712070032', 'info@tmci.uz', 'seed'),
  ('SWISS UNIVERSITY OF MEDICINE AND INFORMATION TECHNOLOGY IN MARGILAN', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT ARCHITECTURE AND CIVIL ENGINEERING UNIVERSITY', 'Toshkent sh, Yunusobod tumani Yangi shahar 9', 'https://taqu.edu.uz', '951423575', 'devon@taqi.uz', 'seed'),
  ('TASHKENT CHEMICAL-TECHNOLOGICAL INSTITUTE', 'Toshkent, Navoiy ko’chasi, 32-uy', 'https://tkti.uz', '712447917', 'info@tkti.uz', 'seed'),
  ('TASHKENT CHEMICAL-TECHNOLOGICAL INSTITUTE, KUNGRAD DEPARTMENT', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT CHEMICAL-TECHNOLOGICAL INSTITUTE, YANGIYER BRANCH', 'Sirdaryo viloyati, Yangiyer shahri, Tinchlik ko‘chasi, 1uy', 'https://tktiyf.uz', '955115856', 'info@tktiyf.uz', 'seed'),
  ('TASHKENT HIGHER COMBINED ARMS COMMAND SCHOOL', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT INSTITUTE OF AUTOMOBILE ROADS', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT INSTITUTE OF FINANCE', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT INSTITUTE OF IRRIGATION AND MELIORATION', 'Toshkent shahar, Qori Niyoziy ko''chasi, 39-uy', 'https://tiiame.uz', '712374668', 'devon@tiiame.uz', 'seed'),
  ('TASHKENT INSTITUTE OF IRRIGATION AND MELIORATION, BUKHARA BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT INSTITUTE OF RAILWAY ENGINEERS', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT INSTITUTE OF TEXTILE AND LIGHT INDUSTRY', 'Toshkent shahri, Shoxjaxon ko''chasi, 5-uy', 'https://web.ttyesi.uz', '712536931', 'pochta@mail.ttyesi.uz', 'seed'),
  ('TASHKENT INTERNATIONAL UNIVERSITY OF EDUCATION', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT ISLAMIC INSTITUTE', 'Toshkent 100002,  Abdulla Qodiriy ko‘chasi, 11-uy', 'https://www.iiau.uz', '712449464', NULL, 'seed'),
  ('TASHKENT MEDICAL ACADEMY', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT MEDICAL ACADEMY, TERMEZ BRANCH', 'TERMIZ SHAHRI, ISLOM KARIMOV KO‘CHASI 64 - UY', 'https://ttatf.uz', '554525586', 'INFO@TTATF.UZ', 'seed'),
  ('TASHKENT MEDICAL ACADEMY, URGENCH BRANCH', 'Urganch shahri Al-Xorazmiy ko''chasi 28-uy', 'https://www.urgfiltma.uz', '622248484', 'ttaurgfil@umail.uz', 'seed'),
  ('TASHKENT PEDIATRIC MEDICAL INSTITUTE', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT PEDIATRIC MEDICAL INSTITUTE, NUKUS BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT PHARMACEUTICAL INSTITUTE', 'Toshkent shahar, Oybek ko‘chasi 45-uy', 'https://pharmi.uz', '712563738', 'info@pharmi.uz', 'seed'),
  ('TASHKENT PHARMACEUTICAL INSTITUTE, KHAZORASP BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT REGIONAL PEDAGOGICAL INSTITUTE', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT STATE AGRARIAN UNIVERSITY', 'Toshkent viloyati, Qibray tumani, Universitet ko''chasi 2-uy', 'http://tdau.agro.uz', '712604382', 'tuag_info@edu.uz', 'seed'),
  ('TASHKENT STATE AGRARIAN UNIVERSITY, NUKUS BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT STATE AGRARIAN UNIVERSITY, SAMARKAND BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT STATE AGRARIAN UNIVERSITY, TERMEZ BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT STATE DENTAL INSTITUTE', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT STATE DENTAL INSTITUTE, ANDIJAN BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT STATE DENTAL INSTITUTE, BUKHARA BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT STATE DENTAL INSTITUTE, NUKUS BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT STATE LAW UNIVERSITY', 'Toshkent shahar, Sayilgoh ko‘chasi, 35-uy', 'https://tsul.uz', '712331395', 'info@tsul.uz', 'seed'),
  ('TASHKENT STATE LAW UNIVERSITY, SPECIALIZED BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT STATE PEDAGOGICAL UNIVERSITY', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT STATE PEDAGOGICAL UNIVERSITY, TERMEZ BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT STATE TECHNICAL UNIVERSITY', 'Toshkent shahri, Universitet ko`chasi 2-uy', 'https://tdtu.uz', '712071464', NULL, 'seed'),
  ('TASHKENT STATE TECHNICAL UNIVERSITY, ALMALYK BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT STATE TECHNICAL UNIVERSITY, KOKAND BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT STATE TECHNICAL UNIVERSITY, NUKUS BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT STATE TECHNICAL UNIVERSITY, TERMEZ BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT STATE TRANSPORT UNIVERSITY', 'Toshkent shahar Mirobod tumani Temiryo‘lchilar ko‘chasi 1-uy', 'https://tstu.uz', '712990001', 'rektorat@tstu.uz', 'seed'),
  ('TASHKENT STATE TRANSPORT UNIVERSITY, KATTAKURGAN BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT STATE UNIVERSITY OF ECONOMICS', 'Toshkent shahri, Islom Karimov ko‘chasi 49', 'https://tsue.uz', '712392866', 'info@tsue.uz', 'seed'),
  ('TASHKENT STATE UNIVERSITY OF ECONOMICS, SAMARKAND BRANCH', 'Samarqand shahri, Professorlar ko''chasi 51-uy', 'https://sbtsue.uz', '662373200', 'sbtsue@edu.uz', 'seed'),
  ('TASHKENT STATE UNIVERSITY OF ORIENTAL STUDIES', 'Toshkent shahri, Amir Temur ko‘chasi 20', 'https://tsuos.uz', '712333424', 'info@tsuos.uz', 'seed'),
  ('TASHKENT STATE UNIVERSITY OF UZBEK LANGUAGE AND LITERATURE', 'Toshkent shahri, Yakkasaroy tumani, Yusuf Xos Hojib ko‘chasi, 103-uy', 'https://tsuull.uz', '712814511', 'interdep@navoiy-uni.uz', 'seed'),
  ('TASHKENT UNIVERSITY OF INFORMATION TECHNOLOGIES', 'Toshkent shahar, Amir Temur shox ko‘chasi 108 uy', 'https://tuit.uz', '712386415', 'info@tuit.uz', 'seed'),
  ('TASHKENT UNIVERSITY OF INFORMATION TECHNOLOGIES, FERGANA BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT UNIVERSITY OF INFORMATION TECHNOLOGIES, NUKUS BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('TASHKENT UNIVERSITY OF INFORMATION TECHNOLOGIES, SAMARKAND BRANCH', 'Samarqand viloyati, Samarqand, Ibn Sino ko''chasi, 2-uy', 'https://samtuit.uz', '662322929', 'samtuit@tuit.uz', 'seed'),
  ('TASHKENT UNIVERSITY OF INFORMATION TECHNOLOGIES, URGENCH BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('TAX ACADEMY', NULL, NULL, NULL, NULL, 'seed'),
  ('TEAM UNIVERSITY IN TASHKENT', NULL, NULL, NULL, NULL, 'seed'),
  ('TEAM UNIVERSITY IN TERMEZ', NULL, NULL, NULL, NULL, 'seed'),
  ('TERMEZ STATE UNIVERSITY', 'Termiz shahri, “Barkamol avlod” ko''chasi 43-uy', 'https://tersu.uz', '762280340', 'info@tersu.uz', 'seed'),
  ('TURIN POLYTECHNIC UNIVERSITY IN TASHKENT', NULL, NULL, NULL, NULL, 'seed'),
  ('TURKISH UNIVERSITY OF ECONOMICS AND TECHNOLOGY, TASHKENT BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('UNIVERSITY OF PISA, TASHKENT BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('UNIVERSITY OF WORLD ECONOMY AND DIPLOMACY', 'Toshkent, Mustaqillik shoh koʻchasi, 54', 'https://www.uwed.uz', '712673950', 'rektorat@uwed.uz', 'seed'),
  ('URGENCH STATE UNIVERSITY', 'Urganch shahar, Hamid Olimjon ko‘chasi, 14-uy', 'https://urdu.uz', '622246680', 'info@urdu.uz', 'seed'),
  ('UZBEK NATIONAL INSTITUTE OF MUSICAL ART', 'Toshkent shahri , Mustaqillik shoh ko‘chasi , 31-uy', 'https://uzmmsi.uz', '712373049', 'info@uzmmsi.uz', 'seed'),
  ('UZBEK-BELARUSIAN JOINT INTERSECTORAL INSTITUTE OF APPLIED TECHNICAL QUALIFICATIONS IN TASHKENT', NULL, NULL, NULL, NULL, 'seed'),
  ('UZBEKISTAN STATE ACADEMY OF CHOREOGRAPHY, URGENCH BRANCH', 'Xorazm viloyati, Urganch tumani, Al-Beruniy ko''chasi 2a-uy', 'https://uzdxauf.uz', '977906070', 'info@uzdxauf.uz', 'seed'),
  ('UZBEKISTAN STATE CONSERVATORY', 'Toshkent viloyati, Shayhontohur tumani, Olmazor ko''chasi 1-uy', 'https://conservatory.uz/', '712394653', 'info@konservatoriya.uz', 'seed'),
  ('UZBEKISTAN STATE INSTITUTE OF ARTS AND CULTURE', 'Toshkent sh. Mirzo Ulug’bek tumani, Yalang’och dahasi 127 «A» uy', 'https://dsmi.uz', '712302802', NULL, 'seed'),
  ('UZBEKISTAN STATE INSTITUTE OF ARTS AND CULTURE, FERGANA REGIONAL BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('UZBEKISTAN STATE INSTITUTE OF ARTS AND CULTURE, NUKUS BRANCH', 'Qoraqalpog''iston Respublikasi, Nukus shahri, Qoraqalpog''iston ko''chasi, raqamsiz uy', 'https://uzdsmi-nf.uz', '612242902', 'fart_info@edu.uz', 'seed'),
  ('UZBEKISTAN STATE UNIVERSITY OF PHYSICAL EDUCATION AND SPORT', 'Toshkent viloyati, Chirchiq shahri, Sportchilar ko''chasi, 19-uy', 'https://www.jtsu.uz', '707171776', 'info@jtsu.uz', 'seed'),
  ('UZBEKISTAN STATE UNIVERSITY OF PHYSICAL EDUCATION AND SPORT, FERGANA BRANCH', NULL, NULL, NULL, NULL, 'seed'),
  ('UZBEKISTAN STATE UNIVERSITY OF PHYSICAL EDUCATION AND SPORT, NUKUS BRANCH', 'Qoraqalpog`iston Respublikasi , Nukus shahri ,Qoraqalpog`iston ko`chasi ,24 -uy', 'https://uzdjtsunf.uz', '612242773', 'ozdjtsunf@edu.uz', 'seed'),
  ('UZBEKISTAN STATE WORLD LANGUAGES UNIVERSITY', 'Toshkent shahri, Kichik Xalqa Yo`li ko`chasi, G-9a mavzesi, 21-a uy', 'https://uzswlu.uz', '712301292', 'uzdjtu@uzswlu.uz', 'seed'),
  ('UZBEKISTAN UNIVERSITY OF JOURNALISM AND MASS COMMUNICATIONS', 'Toshkent shahri, Markaz-5, 88-uy', 'https://www.uzjoku.uz', '712070906', 'info@jmcu.uz', 'seed'),
  ('WEBSTER UNIVERSITY IN TASHKENT', NULL, NULL, NULL, NULL, 'seed'),
  ('WESTMINSTER INTERNATIONAL UNIVERSITY IN TASHKENT', NULL, NULL, NULL, NULL, 'seed'),
  ('YEOJU TECHNICAL INSTITUTE IN TASHKENT', NULL, NULL, NULL, NULL, 'seed'),
  ('ZARMED UNIVERSITY', 'Buxoro viloyati, Shahar: Buxoro, Qayum Murtazoyev ko''chasi, 13A', 'https://zarmeduniver.com/', '655057070', 'info@zarmeduniver.com', 'seed')
ON CONFLICT (name) DO UPDATE SET
  address = EXCLUDED.address,
  website = EXCLUDED.website,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  source = EXCLUDED.source,
  updated_at = NOW();
